/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEX
 */
public class FormAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormAdmin
     */
    
    static Connection cn;
    static Statement s;
    static ResultSet rs;
    
    public FormAdmin() {
        initComponents();
        
        llenarCombo();
    }
    
    public void limpiarCampos(){
        this.jTextCiudad.setText("");
        this.jTextPais.setText("");
        this.jTextFieldNuevaCiudad.setText("");
        this.jTextFieldNuevoDestinoId.setText("");
        this.jTextFieldNuevoPais.setText("");
        this.jTextFieldDestinoIdEliminar.setText("");
        this.jTextNombre.setText("");
        this.jTextFieldEmail.setText("");
        this.jTextFieldApellidoP.setText("");
        this.jTextFieldApellidoM.setText("");
        this.jTextFieldUsername.setText("");
        this.jTextFieldPassword.setText("");
        this.jTextNuevoIdAgente.setText("");
        this.jTextNuevoNombre.setText("");
        this.jTextFieldNuevoApellidoP.setText("");
        this.jTextFieldNuevoApellidoM.setText("");
        this.jTextFieldNuevoUsername.setText("");
        this.jTextFieldNuevoPassword.setText("");
        this.jTextFieldAgenteIDEliminar.setText(""); 
        this.jTextFieldTourNombre.setText("");
        this.jTextFieldTourPrecioBase.setText("");
        this.jTextFieldTourDias.setText("");
        this.jTextFieldTourPrecioTotal.setText("");
        this.jTextFieldTourNuevoNombre.setText("");
        this.jTextFieldTourNuevoPrecioBase.setText("");
        this.jTextFieldTourNuevoDias.setText("");
        this.jTextFieldTourNuevoPrecioTotal.setText("");
        this.jTextFieldTourIDEliminar.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextCiudad = new javax.swing.JTextField();
        jTextPais = new javax.swing.JTextField();
        jButtonRegistrarDestino = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDestinos = new javax.swing.JTable();
        jButtonListarDestinos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNuevoDestinoId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNuevaCiudad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNuevoPais = new javax.swing.JTextField();
        jButtonEditarDestino = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDestinoIdEliminar = new javax.swing.JTextField();
        jButtonEliminarDestino = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextFieldApellidoP = new javax.swing.JTextField();
        jTextFieldApellidoM = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonRegistrarAgente = new javax.swing.JButton();
        jButtonMostrarAgentes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAgentes = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextNuevoNombre = new javax.swing.JTextField();
        jTextFieldNuevoApellidoP = new javax.swing.JTextField();
        jTextFieldNuevoApellidoM = new javax.swing.JTextField();
        jTextFieldNuevoUsername = new javax.swing.JTextField();
        jTextFieldNuevoEmail = new javax.swing.JTextField();
        jTextFieldNuevoPassword = new javax.swing.JTextField();
        jButtonEditarAgente = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextNuevoIdAgente = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldAgenteIDEliminar = new javax.swing.JTextField();
        jButtonEliminarAgente = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldTourNombre = new javax.swing.JTextField();
        jTextFieldTourPrecioBase = new javax.swing.JTextField();
        jTextFieldTourDias = new javax.swing.JTextField();
        jTextFieldTourPrecioTotal = new javax.swing.JTextField();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jButtonTourRegistar = new javax.swing.JButton();
        jButtonMostrarTours = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMostrarTours = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldTourNuevoNombre = new javax.swing.JTextField();
        jTextFieldTourNuevoPrecioBase = new javax.swing.JTextField();
        jTextFieldTourNuevoDias = new javax.swing.JTextField();
        jTextFieldTourNuevoPrecioTotal = new javax.swing.JTextField();
        jComboBoxNuevoDestino = new javax.swing.JComboBox<>();
        jTextFieldTourIDEditar = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jButtonTourEditar = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextFieldTourIDEliminar = new javax.swing.JTextField();
        jButtonEliminarTour = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Registro Destino:");

        jLabel2.setText("Ciudad:");

        jLabel3.setText("Pais:");

        jTextCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiudadKeyTyped(evt);
            }
        });

        jTextPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPaisKeyTyped(evt);
            }
        });

        jButtonRegistrarDestino.setText("Registrar");
        jButtonRegistrarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarDestinoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTableDestinos);

        jButtonListarDestinos.setText("Mostrar Destinos");
        jButtonListarDestinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDestinosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Editar Destino:");

        jLabel5.setText("Id del destino a Editar:");

        jTextFieldNuevoDestinoId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNuevoDestinoIdKeyTyped(evt);
            }
        });

        jLabel6.setText("Nuevo valor de Ciudad:");

        jTextFieldNuevaCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNuevaCiudadKeyTyped(evt);
            }
        });

        jLabel7.setText("Nuevo valor de Pais:");

        jTextFieldNuevoPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNuevoPaisKeyTyped(evt);
            }
        });

        jButtonEditarDestino.setText("Editar");
        jButtonEditarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDestinoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Eliminar Destino:");

        jLabel9.setText("Id del Destino a Eliminar:");

        jTextFieldDestinoIdEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDestinoIdEliminarKeyTyped(evt);
            }
        });

        jButtonEliminarDestino.setText("Eliminar");
        jButtonEliminarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarDestinoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Registro Agente:");

        jLabel11.setText("Nombre:");

        jLabel12.setText("Apellido P. :");

        jLabel13.setText("Apellido M. :");

        jLabel14.setText("UserName:");

        jLabel15.setText("Email:");

        jLabel16.setText("Password:");

        jButtonRegistrarAgente.setText("Registrar");
        jButtonRegistrarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarAgenteActionPerformed(evt);
            }
        });

        jButtonMostrarAgentes.setText("Mostrar Agentes");
        jButtonMostrarAgentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarAgentesActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTableAgentes);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Editar Agente:");

        jLabel18.setText("Nuevo valor de Nombre:");

        jLabel19.setText("Nuevo valor de Apellido P. :");

        jLabel20.setText("Nuevo valor de Apellido M. :");

        jLabel21.setText("Nuevo valor de UserName:");

        jLabel22.setText("Nuevo valor de Email:");

        jLabel23.setText("Nuevo valor de Password:");

        jTextNuevoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNuevoNombreActionPerformed(evt);
            }
        });

        jButtonEditarAgente.setText("Editar");
        jButtonEditarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAgenteActionPerformed(evt);
            }
        });

        jLabel24.setText("Id del Agente a Editar:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Eliminar Agente:");

        jLabel26.setText("Id del Agente a Eliminar:");

        jTextFieldAgenteIDEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAgenteIDEliminarKeyTyped(evt);
            }
        });

        jButtonEliminarAgente.setText("Eliminar");
        jButtonEliminarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAgenteActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Registro Tour");

        jLabel28.setText("Nombre:");

        jLabel29.setText("Precio Base:");

        jLabel30.setText("Dias:");

        jLabel31.setText("Precio Total:");

        jLabel32.setText("Destino:");

        jTextFieldTourPrecioBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourPrecioBaseKeyTyped(evt);
            }
        });

        jTextFieldTourDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourDiasKeyTyped(evt);
            }
        });

        jTextFieldTourPrecioTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourPrecioTotalKeyTyped(evt);
            }
        });

        jButtonTourRegistar.setText("Registrar");
        jButtonTourRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTourRegistarActionPerformed(evt);
            }
        });

        jButtonMostrarTours.setText("Mostar Tours");
        jButtonMostrarTours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarToursActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTableMostrarTours);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Editar Tour:");

        jLabel34.setText("Nuevo valor de Nombre:");

        jLabel35.setText("Nuevo valor de Precio Base:");

        jLabel36.setText("Nuevo valor de Dias:");

        jLabel37.setText("Nuevo valor de Precio Total:");

        jLabel38.setText("Nuevo valor de Destino:");

        jTextFieldTourNuevoPrecioBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourNuevoPrecioBaseKeyTyped(evt);
            }
        });

        jTextFieldTourNuevoDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourNuevoDiasKeyTyped(evt);
            }
        });

        jTextFieldTourNuevoPrecioTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourNuevoPrecioTotalKeyTyped(evt);
            }
        });

        jTextFieldTourIDEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourIDEditarKeyTyped(evt);
            }
        });

        jLabel39.setText("ID del Tour a Editar:");

        jButtonTourEditar.setText("Editar");
        jButtonTourEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTourEditarActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("Eliminar Tour:");

        jLabel41.setText("ID del Tour a Eliminar:");

        jTextFieldTourIDEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTourIDEliminarKeyTyped(evt);
            }
        });

        jButtonEliminarTour.setText("Eliminar");
        jButtonEliminarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarTourActionPerformed(evt);
            }
        });

        jLabel42.setText("* Debe rellenar todos los campos");

        jLabel43.setText("* Debe rellenar todos los campos");

        jLabel44.setText("* Debe rellenar todos los campos");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("BIENVENIDO AL SISTEMA DE ADMINISTRACION DE ONTOUR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRegistrarDestino)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextCiudad)
                                                    .addComponent(jTextPais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel12))
                                                    .addGap(34, 34, 34))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addGap(32, 32, 32)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel31))
                                                .addGap(31, 31, 31)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTourPrecioTotal)
                                            .addComponent(jTextFieldTourDias)
                                            .addComponent(jTextFieldApellidoM, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldApellidoP, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldTourPrecioBase, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldTourNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(51, 51, 51)
                                        .addComponent(jComboBoxDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonRegistrarAgente)
                                            .addComponent(jButtonTourRegistar))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(225, 225, 225)
                                        .addComponent(jButtonMostrarTours))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(jButtonMostrarAgentes)
                                        .addGap(196, 196, 196))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListarDestinos)
                        .addGap(227, 227, 227)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEditarDestino)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(49, 49, 49)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNuevoDestinoId)
                                        .addComponent(jTextFieldNuevaCiudad)
                                        .addComponent(jTextFieldNuevoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextNuevoIdAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNuevoApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNuevoApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNuevoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNuevoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel43))
                                    .addComponent(jButtonEditarAgente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(10, 10, 10)))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonTourEditar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel37)
                                            .addComponent(jLabel38))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTourNuevoPrecioTotal)
                                            .addComponent(jComboBoxNuevoDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTourNuevoDias)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel39)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel44)
                                            .addComponent(jTextFieldTourNuevoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTourIDEditar)
                                            .addComponent(jTextFieldTourNuevoPrecioBase))))
                                .addGap(31, 31, 31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonEliminarDestino)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDestinoIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)))
                            .addComponent(jButtonEliminarAgente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAgenteIDEliminar)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButtonEliminarTour))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldTourIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(jLabel45)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonListarDestinos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonRegistrarDestino))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10))
                            .addComponent(jButtonMostrarAgentes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextFieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegistrarAgente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldDestinoIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addComponent(jButtonEliminarDestino))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldNuevoDestinoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldNuevaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldNuevoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(jButtonEditarDestino)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jTextNuevoIdAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextFieldNuevoApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jTextFieldAgenteIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jButtonEliminarAgente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextFieldNuevoApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldNuevoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldNuevoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFieldNuevoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarAgente)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jButtonMostrarTours))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jTextFieldTourNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29)
                                    .addComponent(jTextFieldTourPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(jTextFieldTourDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(jTextFieldTourPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTourRegistar))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel44)
                            .addComponent(jLabel40))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTourIDEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel41)
                            .addComponent(jTextFieldTourIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(jTextFieldTourNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(jTextFieldTourNuevoPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(jTextFieldTourNuevoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(jTextFieldTourNuevoPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(jComboBoxNuevoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButtonEliminarTour)))
                        .addGap(3, 3, 3)))
                .addComponent(jButtonTourEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarDestinoActionPerformed
        // TODO add your handling code here:
        
        try{
        int minId = 0;
        int id =0;
        String ciudad = this.jTextCiudad.getText();
        String pais = this.jTextPais.getText();
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            rs = s.executeQuery("select MAX(DESTINO_ID) FROM DESTINO");
            
            while(rs.next()){
            
            minId= rs.getInt(1);
            }
            
            id= minId+1;
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("INSERT INTO DESTINO VALUES("+id+",'"+ciudad+"','"+pais+"')");
            JOptionPane.showMessageDialog(rootPane, "INGRESADO CON EXITO");
            limpiarCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL REGISTRAR");
        ex.printStackTrace();
       }
    }//GEN-LAST:event_jButtonRegistrarDestinoActionPerformed

    private void jButtonListarDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDestinosActionPerformed
        // TODO add your handling code here:
        
         try {
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTableDestinos.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
             rs = s.executeQuery("select * from DESTINO ORDER BY DESTINO_ID");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
             modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rs.next()) {
             Object[] fila = new Object[cantidadColumnas];
             for (int i = 0; i < cantidadColumnas; i++) {
               fila[i]=rs.getObject(i+1);
             }
             modelo.addRow(fila);
            }
            rs.close();
            cn.close();
            limpiarCampos();
       } catch (Exception ex) {
        ex.printStackTrace();
       }
    }//GEN-LAST:event_jButtonListarDestinosActionPerformed

    private void jButtonEditarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDestinoActionPerformed
        // TODO add your handling code here:
        
        String nCiudad = this.jTextFieldNuevaCiudad.getText();
        String nPais = this.jTextFieldNuevoPais.getText();
        int dId= Integer.parseInt(jTextFieldNuevoDestinoId.getText());
        
        try{
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //rs = s.executeQuery("select MAX(DESTINO_ID) FROM DESTINO");
            //minId = rs.getInt(1);
            
            //id= minId+1;
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("UPDATE DESTINO SET CIUDAD ='"+nCiudad+"',PAIS = '"+nPais+"' WHERE DESTINO_ID = "+dId+" ");
            JOptionPane.showMessageDialog(rootPane, "EDITADO CON EXITO");
            limpiarCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL EDITAR");
        ex.printStackTrace();
       }
        
    }//GEN-LAST:event_jButtonEditarDestinoActionPerformed

    private void jTextFieldNuevoDestinoIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNuevoDestinoIdKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldNuevoDestinoIdKeyTyped

    private void jTextCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiudadKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo Texto");
        }
        
    }//GEN-LAST:event_jTextCiudadKeyTyped

    private void jTextPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaisKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextPaisKeyTyped

    private void jTextFieldNuevaCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNuevaCiudadKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo texto");
        }
    }//GEN-LAST:event_jTextFieldNuevaCiudadKeyTyped

    private void jTextFieldNuevoPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNuevoPaisKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo texto");
        }
    }//GEN-LAST:event_jTextFieldNuevoPaisKeyTyped

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldDestinoIdEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDestinoIdEliminarKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldDestinoIdEliminarKeyTyped

    private void jButtonEliminarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarDestinoActionPerformed
        // TODO add your handling code here:
        
        int dIdElimianar = Integer.parseInt(jTextFieldDestinoIdEliminar.getText());
        try{
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();

            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("DELETE DESTINO WHERE DESTINO_ID = "+dIdElimianar+" ");
            JOptionPane.showMessageDialog(rootPane, "ELIMINADO CON EXITO");
            limpiarCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL ELIMINAR");
        ex.printStackTrace();
       }
        
    }//GEN-LAST:event_jButtonEliminarDestinoActionPerformed

    private void jButtonRegistrarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarAgenteActionPerformed
        // TODO add your handling code here:
        
        try{
        
        int minId = 0;
        int id =0;
        String nombre= this.jTextNombre.getText();
        String ap_p = this.jTextFieldApellidoP.getText();
        String ap_m = this.jTextFieldApellidoM.getText();
        String username = this.jTextFieldUsername.getText();
        String email = this.jTextFieldEmail.getText();
        String password = this.jTextFieldPassword.getText();
        int rol = 1;
        
        
        
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            rs = s.executeQuery("select MAX(AGENTE_ID) FROM AGENTE");
            
            while(rs.next()){
            
            minId= rs.getInt(1);
            }
            
            id= minId+1;
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("INSERT INTO AGENTE VALUES("+id+",'"+nombre+"','"+ap_p+"','"+ap_m+"','"+username+"','"+email+"','"+password+"','"+rol+"')");
            JOptionPane.showMessageDialog(rootPane, "INGRESADO CON EXITO");
            limpiarCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL REGISTRAR");
        ex.printStackTrace();
       }
        
        
        
    }//GEN-LAST:event_jButtonRegistrarAgenteActionPerformed

    private void jButtonEditarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAgenteActionPerformed
        // TODO add your handling code here:
        int nId = Integer.parseInt(this.jTextNuevoIdAgente.getText());
        String nNombre= this.jTextNuevoNombre.getText();
        String nAp_p = this.jTextFieldNuevoApellidoP.getText();
        String nAp_m = this.jTextFieldNuevoApellidoM.getText();
        String nUsername = this.jTextFieldNuevoUsername.getText();
        String nEmail = this.jTextFieldNuevoEmail.getText();
        String nPassword = this.jTextFieldNuevoPassword.getText();
        
        
        try{
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //rs = s.executeQuery("select MAX(DESTINO_ID) FROM DESTINO");
            //minId = rs.getInt(1);
            
            //id= minId+1;
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("UPDATE AGENTE SET NOMBRE ='"+nNombre+"',AP_PATERNO = '"+nAp_p+"',AP_MATERNO = '"+nAp_m+"',USERNAME = '"+nUsername+"',EMAIL = '"+nEmail+"',PASSWORD = '"+nPassword+"' WHERE AGENTE_ID = "+nId+" ");
            JOptionPane.showMessageDialog(rootPane, "EDITADO CON EXITO");
            limpiarCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL EDITAR");
        ex.printStackTrace();
       }
        
        
    }//GEN-LAST:event_jButtonEditarAgenteActionPerformed
    
   
    
    
    public void llenarCombo(){
        
        
         try {
            //Para establecer el modelo al JTable
           
            //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
             rs = s.executeQuery("select CIUDAD FROM DESTINO ORDER BY DESTINO_ID ");
             
             jComboBoxDestino.addItem("Seleccione");
             jComboBoxNuevoDestino.addItem("Seleccione");
             
             
             while(rs.next()){
             
                 jComboBoxDestino.addItem(rs.getString(1));
                 jComboBoxNuevoDestino.addItem(rs.getString(1));
             
             }
            limpiarCampos();
            
            
            
            
       } catch (Exception ex) {
        ex.printStackTrace();
       }
                
    
    }
    
    private void jTextNuevoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNuevoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNuevoNombreActionPerformed

    private void jButtonMostrarAgentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarAgentesActionPerformed
        // TODO add your handling code here:
        try {
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTableAgentes.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
             rs = s.executeQuery("select * from AGENTE ORDER BY AGENTE_ID");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
             modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rs.next()) {
             Object[] fila = new Object[cantidadColumnas];
             for (int i = 0; i < cantidadColumnas; i++) {
               fila[i]=rs.getObject(i+1);
             }
             modelo.addRow(fila);
            }
            rs.close();
            cn.close();
            limpiarCampos();
       } catch (Exception ex) {
        ex.printStackTrace();
       }
    }//GEN-LAST:event_jButtonMostrarAgentesActionPerformed

    private void jButtonEliminarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAgenteActionPerformed
        // TODO add your handling code here:
     int dIdElimianar = Integer.parseInt(jTextFieldAgenteIDEliminar.getText());
        try{
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();

            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("DELETE AGENTE WHERE AGENTE_ID = "+dIdElimianar+" ");
            JOptionPane.showMessageDialog(rootPane, "ELIMINADO CON EXITO");
            limpiarCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL ELIMINAR");
        ex.printStackTrace();
       }    
        
        
    }//GEN-LAST:event_jButtonEliminarAgenteActionPerformed

    private void jButtonTourRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTourRegistarActionPerformed
        // TODO add your handling code here:
        
        try{
        
        int minId = 0;
        int id =0;
        String nombreTour= this.jTextFieldTourNombre.getText();
        int precioBase = Integer.parseInt(this.jTextFieldTourPrecioBase.getText());
        int dias = Integer.parseInt(this.jTextFieldTourDias.getText());
        int precioTotal = Integer.parseInt(this.jTextFieldTourPrecioTotal.getText());
        int destinoId = this.jComboBoxDestino.getSelectedIndex();
        
        
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            rs = s.executeQuery("select MAX(TOUR_ID) FROM TOUR");
            
            while(rs.next()){
            
            minId= rs.getInt(1);
            }
            
            id= minId+1;
            if(destinoId<=0){
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un Destino");
            }else{
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("INSERT INTO TOUR VALUES("+id+",'"+nombreTour+"',"+precioBase+","+dias+","+precioTotal+","+destinoId+")");
            JOptionPane.showMessageDialog(rootPane, "INGRESADO CON EXITO");
            limpiarCampos();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL REGISTRAR");
        ex.printStackTrace();
       }
    }//GEN-LAST:event_jButtonTourRegistarActionPerformed

    private void jButtonMostrarToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarToursActionPerformed
        // TODO add your handling code here:
        try {
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTableMostrarTours.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
             rs = s.executeQuery("select * from TOUR ORDER BY TOUR_ID");
            //Obteniendo la informacion de las columnas que estan siendo consultadas
            ResultSetMetaData rsMd = rs.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
             modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rs.next()) {
             Object[] fila = new Object[cantidadColumnas];
             for (int i = 0; i < cantidadColumnas; i++) {
               fila[i]=rs.getObject(i+1);
             }
             modelo.addRow(fila);
            }
            rs.close();
            cn.close();
            limpiarCampos();
       } catch (Exception ex) {
        ex.printStackTrace();
       }
        
    }//GEN-LAST:event_jButtonMostrarToursActionPerformed

    private void jButtonTourEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTourEditarActionPerformed
        // TODO add your handling code here:
        
        int nId = Integer.parseInt(this.jTextFieldTourIDEditar.getText());
        
        String nNombreTour= this.jTextFieldTourNuevoNombre.getText();
        int nPrecioBase = Integer.parseInt(this.jTextFieldTourNuevoPrecioBase.getText());
        int nDias = Integer.parseInt(this.jTextFieldTourNuevoDias.getText());
        int nPrecioTotal = Integer.parseInt(this.jTextFieldTourNuevoPrecioTotal.getText());
        int nDestinoId = this.jComboBoxNuevoDestino.getSelectedIndex();
        
        
        try{
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();
            if(nDestinoId<=0){
            JOptionPane.showMessageDialog(rootPane, "Debe Seleccionar un Destino");
            }else{
            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("UPDATE TOUR SET NOMBRE_TOURS ='"+nNombreTour+"',PRECIO_BASE = "+nPrecioBase+",DIAS = "+nDias+",PRECIO_TOTAL = "+nPrecioTotal+",DESTINO_DESTINO_ID = "+nDestinoId+" WHERE TOUR_ID = "+nId+" ");
            JOptionPane.showMessageDialog(rootPane, "EDITADO CON EXITO");
            limpiarCampos();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL EDITAR");
        ex.printStackTrace();
       }
    }//GEN-LAST:event_jButtonTourEditarActionPerformed

    private void jButtonEliminarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTourActionPerformed
        // TODO add your handling code here:
        int dIdElimianar = Integer.parseInt(jTextFieldTourIDEliminar.getText());
        try{
        
        //Para conectarnos a nuestra base de datos
            String url = "jdbc:oracle:thin:@ontourbd.ct6x72g7c3id.us-east-2.rds.amazonaws.com:1521:orcl";
            // Establecemos los valores de cadena de conexión, usuario y contraseña
            cn = DriverManager.getConnection(url, "Portafolio02", "Portafolio123");
            //Para ejecutar la consulta
            s = cn.createStatement();

            //Ejecutamos la consulta y los datos lo almacenamos en un ResultSet
            rs = s.executeQuery("DELETE TOUR WHERE TOUR_ID = "+dIdElimianar+" ");
            JOptionPane.showMessageDialog(rootPane, "ELIMINADO CON EXITO");
            limpiarCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL ELIMINAR");
        ex.printStackTrace();
       }   
        
    }//GEN-LAST:event_jButtonEliminarTourActionPerformed

    private void jTextFieldTourDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourDiasKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourDiasKeyTyped

    private void jTextFieldTourPrecioBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourPrecioBaseKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourPrecioBaseKeyTyped

    private void jTextFieldTourPrecioTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourPrecioTotalKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourPrecioTotalKeyTyped

    private void jTextFieldTourIDEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourIDEditarKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourIDEditarKeyTyped

    private void jTextFieldTourNuevoPrecioBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourNuevoPrecioBaseKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourNuevoPrecioBaseKeyTyped

    private void jTextFieldTourNuevoDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourNuevoDiasKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourNuevoDiasKeyTyped

    private void jTextFieldTourNuevoPrecioTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourNuevoPrecioTotalKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourNuevoPrecioTotalKeyTyped

    private void jTextFieldTourIDEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTourIDEliminarKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldTourIDEliminarKeyTyped

    private void jTextFieldAgenteIDEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAgenteIDEliminarKeyTyped
        // TODO add your handling code here:
         char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_jTextFieldAgenteIDEliminarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarAgente;
    private javax.swing.JButton jButtonEditarDestino;
    private javax.swing.JButton jButtonEliminarAgente;
    private javax.swing.JButton jButtonEliminarDestino;
    private javax.swing.JButton jButtonEliminarTour;
    private javax.swing.JButton jButtonListarDestinos;
    private javax.swing.JButton jButtonMostrarAgentes;
    private javax.swing.JButton jButtonMostrarTours;
    private javax.swing.JButton jButtonRegistrarAgente;
    private javax.swing.JButton jButtonRegistrarDestino;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTourEditar;
    private javax.swing.JButton jButtonTourRegistar;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxNuevoDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAgentes;
    private javax.swing.JTable jTableDestinos;
    private javax.swing.JTable jTableMostrarTours;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextFieldAgenteIDEliminar;
    private javax.swing.JTextField jTextFieldApellidoM;
    private javax.swing.JTextField jTextFieldApellidoP;
    private javax.swing.JTextField jTextFieldDestinoIdEliminar;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNuevaCiudad;
    private javax.swing.JTextField jTextFieldNuevoApellidoM;
    private javax.swing.JTextField jTextFieldNuevoApellidoP;
    private javax.swing.JTextField jTextFieldNuevoDestinoId;
    private javax.swing.JTextField jTextFieldNuevoEmail;
    private javax.swing.JTextField jTextFieldNuevoPais;
    private javax.swing.JTextField jTextFieldNuevoPassword;
    private javax.swing.JTextField jTextFieldNuevoUsername;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldTourDias;
    private javax.swing.JTextField jTextFieldTourIDEditar;
    private javax.swing.JTextField jTextFieldTourIDEliminar;
    private javax.swing.JTextField jTextFieldTourNombre;
    private javax.swing.JTextField jTextFieldTourNuevoDias;
    private javax.swing.JTextField jTextFieldTourNuevoNombre;
    private javax.swing.JTextField jTextFieldTourNuevoPrecioBase;
    private javax.swing.JTextField jTextFieldTourNuevoPrecioTotal;
    private javax.swing.JTextField jTextFieldTourPrecioBase;
    private javax.swing.JTextField jTextFieldTourPrecioTotal;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNuevoIdAgente;
    private javax.swing.JTextField jTextNuevoNombre;
    private javax.swing.JTextField jTextPais;
    // End of variables declaration//GEN-END:variables
}
